Development
Hy-An/AleProyecto1- pull request #1
Opened 2021-04-30 18:03 UTC by alemmaz

-acomodando un poco header, footer y main
-rama development creada

2021-05-04 00:38 UTC, nathan-hyan approved these changes
🥇

2021-05-18 18:17 UTC, nathan-hyan requested changes
Some comments. Remember to close this PR and open a new one on a new branch once this one gets approved. So there's no further confusion.

2021-05-18 18:17 UTC, nathan-hyan commented on .vscode/settings.json
> +    "liveServer.settings.port": 5501
Add this file to a `.gitignore` file. Ask me if you need help with this

2021-05-18 18:17 UTC, nathan-hyan commented on index.html
> +        <li id="slide5"><img src="img/sli1.jpg" alt="" class="imgslider"></ li>
Put the description of the image in the `alt` prop. Don't leave it empty

2021-05-18 18:17 UTC, nathan-hyan commented on index.html
> +            <li><a href="#slide5">5<//a></ li>
Fix the `<//a>` typo here, it's `</a>`

2021-05-18 18:17 UTC, nathan-hyan commented on index.html
> +
same here with the `alt` in the images

2021-05-18 18:17 UTC, nathan-hyan commented on index.html
> +                <img  src="img/footer5.jpg" alt="" class="comicsG">
same here

2021-05-18 18:17 UTC, nathan-hyan commented on style.css
> +
Use prettier so there's no excess of empty spaces. Also, remove comments when pushing code for a PR. The only comments that are permitted are `TODO: Need fixing yadayadyadyad`

2021-05-20 17:16 UTC, alemmaz commented
still problem with slider, I can´t fix alignment with layout

2021-05-20 17:20 UTC, nathan-hyan approved these changes
Fix spacing and this is done! congrats 🥇

2021-05-27 14:56 UTC, nathan-hyan approved these changes
🥇

2021-05-27 14:56 UTC, nathan-hyan commented
Close this PR, and make a new one

2021-05-27 14:59 UTC, merged